process.env.APP_NAME = "acsp-manage-users-web";
process.env.LOG_LEVEL = "info";
process.env.NODE_ENV = "dev";
process.env.NODE_PORT = "3000";
process.env.NUNJUCKS_LOADER_WATCH = "false";
process.env.NUNJUCKS_LOADER_NO_CACHE = "true";
process.env.CHS_URL = "http://chsurl.co";

process.env.API_URL = "http://testapi.co";
process.env.COOKIE_SECRET = "Xy6onkjQWF0TkRn0hfdqUw==";
process.env.COOKIE_DOMAIN = "cookie domain";
process.env.CACHE_SERVER = "test";
process.env.COOKIE_NAME = "cookie_name";
process.env.INTERNAL_API_URL = "api_url";
process.env.CHS_INTERNAL_API_KEY = "key";
process.env.ACCOUNT_URL = "account_url";
process.env.FEATURE_FLAG_SHOW_TELL_US_YOUVE_VERIFIED_A_PERSONS_IDENTITY = "true";
process.env.FEATURE_FLAG_IDENTITY_VERIFICATION_REPORTING = "true";
process.env.FEATURE_FLAG_SHOW_UPDATE_AUTHORISED_AGENT_DETAILS = "true";
process.env.FEATURE_FLAG_SHOW_FILE_AS_AUTHORISED_AGENT = "true";
process.env.FEATURE_FLAG_SHOW_CLOSE_AUTHORISED_AGENT = "true";
